# Generated by Django 4.0 on 2021-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('duration', models.FloatField()),
                ('last_play', models.DateTimeField()),
                ('song_file', models.FileField(upload_to='')),
            ],
        ),
    ]
